### ISSUE TITLE
获取UUID为空，请教

### ISSUE THREAD

**Issue by TracyEminem** [a1anwang/okble#5]
我调用这两个方法获得的UUID都是空的，BLEScanResult.getServiceUuids(),BLEScanResult.getBluetoothDevice().getUuids()，好像必须点击连接以后才能获取到UUID

**Comment by a1anwang** [comment]
BLEScanResult里面获取的uuid是BLE设备的广播里的UUID，连接设备之后获取的UUID是用于设备通讯的UUID，这2个UUID是不一样的哦。广播里是可以没有UUID的。

**Comment by TracyEminem** [comment]
好的。
